// app/layout.tsx
import type { Metadata } from "next";
import { Inter, Orbitron } from "next/font/google";
import { Toaster } from "sonner";
import "./globals.css";
import { AuthProvider } from '@/lib/components/auth/AuthProvider';

// Initialize Inter font (default)
const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

// Initialize Orbitron font
const orbitron = Orbitron({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-orbitron",
});

export const metadata: Metadata = {
  title: "Gloro",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${inter.variable} ${orbitron.variable}`}
    >
      <body className="font-sans antialiased" suppressHydrationWarning>
        <AuthProvider>
        {children}
        <Toaster position="top-right" richColors />
          </AuthProvider>
      </body>
    </html>
  );
}
